# Local configuration for the rubocop linter.

# Inherit from the working file.
inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'pkg/**/*'
    - 'vendor/**/*'

Lint/UselessAssignment:
  Exclude:
    - 'examples/example_basic.rb'

Gemspec/DevelopmentDependencies:
  Enabled: false
