# Build and test the RubyTree library.
#
# This runs as a Github Action.

name: Build and Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.2", "3.3", "3.4"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: rm -rf pkg
      - run: bundle exec rake clobber
      - run: bundle exec rake test:all
      - run: bundle exec rake doc:yard
        if: matrix.ruby == '3.4'
      - run: bundle exec rake gemspec
      - run: bundle exec rake gem:package
